Repository im-Michelle/DevMura, pull requests merged in 2023-05, with the labels that each got.

#12 se agrego el componente de footer
  src/components/Footer/index.jsx
  src/pages/Contact-us/index.jsx
  src/pages/Home/index.jsx
Labels: new component

#49 Goyo
  dist/assets/index-56c5f4be.js
  dist/assets/index-7cce4461.js
  dist/index.html
  package-lock.json
  package.json
  src/Utilities/IconDictionary/iconsD.jsx
  src/components/Button/index.jsx
  src/data/user.js
  src/pages/Home/index.jsx
  src/pages/Profile/components/LearningInterests.jsx
  src/pages/Profile/components/PersonalDescription.jsx
  src/pages/Profile/components/ProgramingLeng.jsx
  src/pages/Profile/index.jsx
  src/pages/TermsOfService/index.jsx
Labels: enhancement

#59 sin cambios
  src/data/user.js
  src/pages/Profile/index.jsx
Labels: bug fix
